### ISSUE TITLE
shields.io

### ISSUE THREAD

**Issue by yoshuawuyts** [badges/stability-badges#2]
Hi, first off I want to congratulate you on this project, I can see me using it in the near future. I'm curious though, why aren't you using the default [gittip shields](http://shields.io/) shields. I think if you'd adopt them your badges would go along nicely with Travis and the likes.

**Comment by hughsk** [comment]
Hi @yoshuawuyts, glad the badges could be of use to you! I wasn't aware of shields.io when I made these badges, but I think they're ok as is: [drone.io](http://drone.io), [david-dm.org](http://david-dm.org) and [nodei.co](http://nodei.co/) all have their own style of badges too.

If there's enough interest I can always add a shields.io set of badges, but I feel these are fine as they are now :)

**Comment by yoshuawuyts** [comment]
Great to hear back from you. Actually david-dm added [dual support](https://github.com/alanshaw/david/issues/36) for both badge styles a few weeks ago. I wasn't sure if you were aware of shields.io though, but I guess now you are :)
